services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: pimcore
      MYSQL_USER: pimcore
      MYSQL_PASSWORD: pimcore
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: unless-stopped

  php:
    image: pimcore/pimcore:php8.1-latest
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - pimcore-app:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      PHP_IDE_CONFIG: serverName=localhost

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - pimcore-app:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  db-data:
  pimcore-app:
